[common]
build_type = debug
build_src_filter =
    +<common/**>
test_filter =
    common/*
build_flags =
    -std=gnu++17
build_unflags = -std=gnu++11
lib_deps=
    bblanchon/ArduinoJson
check_flags =
    cppcheck: --suppress=preprocessorErrorDirective
    cppcheck: --suppress=preprocessorErrorDirective:*/ArduinoJson/*

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 9600
upload_speed = 921600

build_src_filter =
    ${common.build_src_filter}
    +<esp32/**>
test_filter =
    ${common.test_filter}
    esp32/*
board_build.filesystem = littlefs
lib_deps=
    ${common.lib_deps}
    TFT_eSPI
    LiquidCrystal_I2C
build_flags =
    ${common.build_flags}
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DPIO_ENV_ESP
build_unflags =
    ${common.build_unflags}
check_flags =
    cppcheck: --suppress=preprocessorErrorDirective
    cppcheck: --suppress=preprocessorErrorDirective:*/ArduinoJson/*

[env:desktop]
platform = native

build_src_filter =
    ${common.build_src_filter}
    +<desktop/**>
test_filter =
    ${common.test_filter}
    desktop/*
build_flags =
    ${common.build_flags}
    -DPIO_ENV_DESKTOP
build_unflags =
    ${common.build_unflags}
lib_deps=
    ${common.lib_deps}
check_flags =
    cppcheck: --suppress=preprocessorErrorDirective
    cppcheck: --suppress=preprocessorErrorDirective:*/ArduinoJson/*
