[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 9600
upload_speed = 921600
build_type = debug

board_build.filesystem = littlefs
lib_deps= 
    bblanchon/ArduinoJson
    TFT_eSPI
    LiquidCrystal_I2C
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
